// Generated by gencpp from file quizpkg/subtractsrvResponse.msg
// DO NOT EDIT!


#ifndef QUIZPKG_MESSAGE_SUBTRACTSRVRESPONSE_H
#define QUIZPKG_MESSAGE_SUBTRACTSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quizpkg
{
template <class ContainerAllocator>
struct subtractsrvResponse_
{
  typedef subtractsrvResponse_<ContainerAllocator> Type;

  subtractsrvResponse_()
    : sub(0)  {
    }
  subtractsrvResponse_(const ContainerAllocator& _alloc)
    : sub(0)  {
  (void)_alloc;
    }



   typedef int64_t _sub_type;
  _sub_type sub;





  typedef boost::shared_ptr< ::quizpkg::subtractsrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quizpkg::subtractsrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct subtractsrvResponse_

typedef ::quizpkg::subtractsrvResponse_<std::allocator<void> > subtractsrvResponse;

typedef boost::shared_ptr< ::quizpkg::subtractsrvResponse > subtractsrvResponsePtr;
typedef boost::shared_ptr< ::quizpkg::subtractsrvResponse const> subtractsrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quizpkg::subtractsrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quizpkg::subtractsrvResponse_<ContainerAllocator1> & lhs, const ::quizpkg::subtractsrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sub == rhs.sub;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quizpkg::subtractsrvResponse_<ContainerAllocator1> & lhs, const ::quizpkg::subtractsrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quizpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quizpkg::subtractsrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quizpkg::subtractsrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quizpkg::subtractsrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5a20f081f63696a93c70a6384724004";
  }

  static const char* value(const ::quizpkg::subtractsrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5a20f081f63696aULL;
  static const uint64_t static_value2 = 0x93c70a6384724004ULL;
};

template<class ContainerAllocator>
struct DataType< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quizpkg/subtractsrvResponse";
  }

  static const char* value(const ::quizpkg::subtractsrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sub\n"
;
  }

  static const char* value(const ::quizpkg::subtractsrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sub);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct subtractsrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quizpkg::subtractsrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quizpkg::subtractsrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "sub: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sub);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUIZPKG_MESSAGE_SUBTRACTSRVRESPONSE_H
