// Generated by gencpp from file quizpkg/subtractsrvRequest.msg
// DO NOT EDIT!


#ifndef QUIZPKG_MESSAGE_SUBTRACTSRVREQUEST_H
#define QUIZPKG_MESSAGE_SUBTRACTSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quizpkg
{
template <class ContainerAllocator>
struct subtractsrvRequest_
{
  typedef subtractsrvRequest_<ContainerAllocator> Type;

  subtractsrvRequest_()
    : a(0)
    , b(0)  {
    }
  subtractsrvRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::quizpkg::subtractsrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quizpkg::subtractsrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct subtractsrvRequest_

typedef ::quizpkg::subtractsrvRequest_<std::allocator<void> > subtractsrvRequest;

typedef boost::shared_ptr< ::quizpkg::subtractsrvRequest > subtractsrvRequestPtr;
typedef boost::shared_ptr< ::quizpkg::subtractsrvRequest const> subtractsrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quizpkg::subtractsrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quizpkg::subtractsrvRequest_<ContainerAllocator1> & lhs, const ::quizpkg::subtractsrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quizpkg::subtractsrvRequest_<ContainerAllocator1> & lhs, const ::quizpkg::subtractsrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quizpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quizpkg::subtractsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quizpkg::subtractsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quizpkg::subtractsrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::quizpkg::subtractsrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quizpkg/subtractsrvRequest";
  }

  static const char* value(const ::quizpkg::subtractsrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::quizpkg::subtractsrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct subtractsrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quizpkg::subtractsrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quizpkg::subtractsrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUIZPKG_MESSAGE_SUBTRACTSRVREQUEST_H
