// Generated by gencpp from file quizpkg/subtractsrv.msg
// DO NOT EDIT!


#ifndef QUIZPKG_MESSAGE_SUBTRACTSRV_H
#define QUIZPKG_MESSAGE_SUBTRACTSRV_H

#include <ros/service_traits.h>


#include <quizpkg/subtractsrvRequest.h>
#include <quizpkg/subtractsrvResponse.h>


namespace quizpkg
{

struct subtractsrv
{

typedef subtractsrvRequest Request;
typedef subtractsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct subtractsrv
} // namespace quizpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quizpkg::subtractsrv > {
  static const char* value()
  {
    return "9eb98bb9850f1c1774cf3ff3d5ba1aec";
  }

  static const char* value(const ::quizpkg::subtractsrv&) { return value(); }
};

template<>
struct DataType< ::quizpkg::subtractsrv > {
  static const char* value()
  {
    return "quizpkg/subtractsrv";
  }

  static const char* value(const ::quizpkg::subtractsrv&) { return value(); }
};


// service_traits::MD5Sum< ::quizpkg::subtractsrvRequest> should match
// service_traits::MD5Sum< ::quizpkg::subtractsrv >
template<>
struct MD5Sum< ::quizpkg::subtractsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quizpkg::subtractsrv >::value();
  }
  static const char* value(const ::quizpkg::subtractsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quizpkg::subtractsrvRequest> should match
// service_traits::DataType< ::quizpkg::subtractsrv >
template<>
struct DataType< ::quizpkg::subtractsrvRequest>
{
  static const char* value()
  {
    return DataType< ::quizpkg::subtractsrv >::value();
  }
  static const char* value(const ::quizpkg::subtractsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quizpkg::subtractsrvResponse> should match
// service_traits::MD5Sum< ::quizpkg::subtractsrv >
template<>
struct MD5Sum< ::quizpkg::subtractsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quizpkg::subtractsrv >::value();
  }
  static const char* value(const ::quizpkg::subtractsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quizpkg::subtractsrvResponse> should match
// service_traits::DataType< ::quizpkg::subtractsrv >
template<>
struct DataType< ::quizpkg::subtractsrvResponse>
{
  static const char* value()
  {
    return DataType< ::quizpkg::subtractsrv >::value();
  }
  static const char* value(const ::quizpkg::subtractsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUIZPKG_MESSAGE_SUBTRACTSRV_H
