// Generated by gencpp from file tatrialpkg/AddTwoInitRequest.msg
// DO NOT EDIT!


#ifndef TATRIALPKG_MESSAGE_ADDTWOINITREQUEST_H
#define TATRIALPKG_MESSAGE_ADDTWOINITREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tatrialpkg
{
template <class ContainerAllocator>
struct AddTwoInitRequest_
{
  typedef AddTwoInitRequest_<ContainerAllocator> Type;

  AddTwoInitRequest_()
    : a(0)
    , b(0)  {
    }
  AddTwoInitRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoInitRequest_

typedef ::tatrialpkg::AddTwoInitRequest_<std::allocator<void> > AddTwoInitRequest;

typedef boost::shared_ptr< ::tatrialpkg::AddTwoInitRequest > AddTwoInitRequestPtr;
typedef boost::shared_ptr< ::tatrialpkg::AddTwoInitRequest const> AddTwoInitRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator1> & lhs, const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator1> & lhs, const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tatrialpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tatrialpkg/AddTwoInitRequest";
  }

  static const char* value(const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoInitRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tatrialpkg::AddTwoInitRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TATRIALPKG_MESSAGE_ADDTWOINITREQUEST_H
