// Generated by gencpp from file tatrialpkg/AddTwoInit.msg
// DO NOT EDIT!


#ifndef TATRIALPKG_MESSAGE_ADDTWOINIT_H
#define TATRIALPKG_MESSAGE_ADDTWOINIT_H

#include <ros/service_traits.h>


#include <tatrialpkg/AddTwoInitRequest.h>
#include <tatrialpkg/AddTwoInitResponse.h>


namespace tatrialpkg
{

struct AddTwoInit
{

typedef AddTwoInitRequest Request;
typedef AddTwoInitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInit
} // namespace tatrialpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tatrialpkg::AddTwoInit > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tatrialpkg::AddTwoInit&) { return value(); }
};

template<>
struct DataType< ::tatrialpkg::AddTwoInit > {
  static const char* value()
  {
    return "tatrialpkg/AddTwoInit";
  }

  static const char* value(const ::tatrialpkg::AddTwoInit&) { return value(); }
};


// service_traits::MD5Sum< ::tatrialpkg::AddTwoInitRequest> should match
// service_traits::MD5Sum< ::tatrialpkg::AddTwoInit >
template<>
struct MD5Sum< ::tatrialpkg::AddTwoInitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tatrialpkg::AddTwoInit >::value();
  }
  static const char* value(const ::tatrialpkg::AddTwoInitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tatrialpkg::AddTwoInitRequest> should match
// service_traits::DataType< ::tatrialpkg::AddTwoInit >
template<>
struct DataType< ::tatrialpkg::AddTwoInitRequest>
{
  static const char* value()
  {
    return DataType< ::tatrialpkg::AddTwoInit >::value();
  }
  static const char* value(const ::tatrialpkg::AddTwoInitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tatrialpkg::AddTwoInitResponse> should match
// service_traits::MD5Sum< ::tatrialpkg::AddTwoInit >
template<>
struct MD5Sum< ::tatrialpkg::AddTwoInitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tatrialpkg::AddTwoInit >::value();
  }
  static const char* value(const ::tatrialpkg::AddTwoInitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tatrialpkg::AddTwoInitResponse> should match
// service_traits::DataType< ::tatrialpkg::AddTwoInit >
template<>
struct DataType< ::tatrialpkg::AddTwoInitResponse>
{
  static const char* value()
  {
    return DataType< ::tatrialpkg::AddTwoInit >::value();
  }
  static const char* value(const ::tatrialpkg::AddTwoInitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TATRIALPKG_MESSAGE_ADDTWOINIT_H
