// Generated by gencpp from file tatrialpkg/AddTwoInitResponse.msg
// DO NOT EDIT!


#ifndef TATRIALPKG_MESSAGE_ADDTWOINITRESPONSE_H
#define TATRIALPKG_MESSAGE_ADDTWOINITRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tatrialpkg
{
template <class ContainerAllocator>
struct AddTwoInitResponse_
{
  typedef AddTwoInitResponse_<ContainerAllocator> Type;

  AddTwoInitResponse_()
    : sum(0)  {
    }
  AddTwoInitResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoInitResponse_

typedef ::tatrialpkg::AddTwoInitResponse_<std::allocator<void> > AddTwoInitResponse;

typedef boost::shared_ptr< ::tatrialpkg::AddTwoInitResponse > AddTwoInitResponsePtr;
typedef boost::shared_ptr< ::tatrialpkg::AddTwoInitResponse const> AddTwoInitResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator1> & lhs, const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator1> & lhs, const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tatrialpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tatrialpkg/AddTwoInitResponse";
  }

  static const char* value(const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
;
  }

  static const char* value(const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoInitResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tatrialpkg::AddTwoInitResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TATRIALPKG_MESSAGE_ADDTWOINITRESPONSE_H
